// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace EmployeeManagement.API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220511063344_initial-data")]
    partial class initialdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50575e92-4a29-4557-9a4b-8a96278a6dbe"),
                            Address = "House 498, Street 105, Model Town, Humak, Islamabad",
                            Country = "Pakistan",
                            Name = "IT_Solutions Ltd"
                        },
                        new
                        {
                            Id = new Guid("c65761ae-89fa-4c5c-98b6-4f55eb454f59"),
                            Address = "House 1228i, Usman Block, Bahria Phase 8, Rawalpindi",
                            Country = "Pakistan",
                            Name = "Admin_Solutions Ltd"
                        });
                });

            modelBuilder.Entity("Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3070e5f0-90a6-4ccd-82ca-dd437e1ba295"),
                            Age = 41,
                            CompanyId = new Guid("50575e92-4a29-4557-9a4b-8a96278a6dbe"),
                            Name = "Saqib Razzaq",
                            Position = "CEO"
                        },
                        new
                        {
                            Id = new Guid("c4ca2c04-0f10-4324-992f-33e41e9f006e"),
                            Age = 38,
                            CompanyId = new Guid("50575e92-4a29-4557-9a4b-8a96278a6dbe"),
                            Name = "Rabia Basri",
                            Position = "Director"
                        },
                        new
                        {
                            Id = new Guid("b5279d7a-d4ae-42a7-871c-7997ab9bb2a2"),
                            Age = 11,
                            CompanyId = new Guid("c65761ae-89fa-4c5c-98b6-4f55eb454f59"),
                            Name = "Shaheer Saqib",
                            Position = "CEO"
                        });
                });

            modelBuilder.Entity("Entities.Employee", b =>
                {
                    b.HasOne("Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
